# Generated by Django 4.2.7 on 2024-02-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServEase', '0004_remove_booking_booking_time_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
